# Example Judge Panel Configuration for Rubric Kit
# ===================================================
# This file demonstrates how to configure a multi-judge panel for more
# reliable and robust evaluation results.

judge_panel:
  # List of judges (LLM models) that will evaluate each criterion
  # Each judge evaluates independently, then results are combined via consensus
  judges:
    - name: primary
      model: gpt-4
      # API key can be null to use OPENAI_API_KEY environment variable
      api_key: null
      # Base URL can be null to use default OpenAI endpoint
      base_url: null
    
    - name: secondary
      model: gpt-4-turbo
      api_key: null
      base_url: null
    
    - name: tertiary
      model: gpt-4
      api_key: null
      base_url: null
    
    # Example: Using a different API provider (e.g., Anthropic via OpenRouter)
    # - name: claude_judge
    #   model: claude-3-5-sonnet-20241022
    #   api_key: ${ANTHROPIC_API_KEY}
    #   base_url: https://api.anthropic.com/v1
    
    # Example: Using OpenRouter for diverse model access
    # - name: openrouter_judge
    #   model: anthropic/claude-3-5-sonnet
    #   api_key: ${OPENROUTER_API_KEY}
    #   base_url: https://openrouter.ai/api/v1
  
  # Execution configuration: How judges are called
  execution:
    # Mode options:
    # - "sequential": Call judges one by one (safest for rate limits, default)
    # - "parallel": Call all judges simultaneously (fastest, may hit rate limits)
    # - "batched": Call judges in batches (balanced approach)
    mode: sequential
    
    # Batch size (only used when mode is "batched")
    # Determines how many judges are called simultaneously in each batch
    batch_size: 2
    
    # Timeout in seconds for each individual judge call
    # If a judge takes longer than this, it will be considered failed
    timeout: 30
  
  # Consensus configuration: How judge votes are combined
  consensus:
    # Mode options:
    # - "quorum": Specific number of judges must agree (threshold required)
    # - "majority": More than 50% must agree (threshold auto-calculated)
    # - "unanimous": All judges must agree (threshold = number of judges)
    mode: quorum
    
    # Threshold: Minimum number of judges that must agree on the same result
    # Required for "quorum" mode, auto-calculated for "majority" and "unanimous"
    # In this example with 3 judges and threshold 2: at least 2 must agree
    threshold: 2
    
    # What to do when consensus is not reached:
    # - "fail": Use conservative approach (minimum score or fail) - DEFAULT
    # - "median": Use median of all judge scores (for score-based criteria)
    # - "most_common": Use most frequent result (ties broken conservatively)
    on_no_consensus: fail


# ============================================================================
# Alternative Configurations
# ============================================================================

# Example 1: Single Judge (backward compatible)
# ----------------------------------------------
# judge_panel:
#   judges:
#     - name: default
#       model: gpt-4
#   execution:
#     mode: sequential
#   consensus:
#     mode: unanimous

# Example 2: Majority Consensus with Parallel Execution
# ------------------------------------------------------
# judge_panel:
#   judges:
#     - name: judge_1
#       model: gpt-4
#     - name: judge_2
#       model: gpt-4-turbo
#     - name: judge_3
#       model: gpt-4
#     - name: judge_4
#       model: gpt-4-turbo
#     - name: judge_5
#       model: gpt-4
#   execution:
#     mode: parallel
#     timeout: 60
#   consensus:
#     mode: majority  # Automatically requires 3 out of 5 judges to agree
#     on_no_consensus: most_common

# Example 3: Diverse Model Panel with Batched Execution
# -------------------------------------------------------
# judge_panel:
#   judges:
#     - name: openai_1
#       model: gpt-4
#     - name: openai_2
#       model: gpt-4-turbo
#     - name: openai_3
#       model: gpt-4o
#     - name: claude_1
#       model: claude-3-5-sonnet-20241022
#       api_key: ${ANTHROPIC_API_KEY}
#       base_url: https://api.anthropic.com/v1
#     - name: claude_2
#       model: claude-3-opus-20240229
#       api_key: ${ANTHROPIC_API_KEY}
#       base_url: https://api.anthropic.com/v1
#   execution:
#     mode: batched
#     batch_size: 2  # Process 2 judges at a time
#     timeout: 45
#   consensus:
#     mode: quorum
#     threshold: 3  # 3 out of 5 must agree
#     on_no_consensus: median

# Example 4: High-Confidence Panel (Unanimous Required)
# ------------------------------------------------------
# judge_panel:
#   judges:
#     - name: judge_1
#       model: gpt-4
#     - name: judge_2
#       model: gpt-4-turbo
#     - name: judge_3
#       model: gpt-4
#   execution:
#     mode: sequential
#   consensus:
#     mode: unanimous  # All 3 judges must agree
#     on_no_consensus: fail  # Conservative: use lowest score if no consensus


# ============================================================================
# Usage
# ============================================================================
# rubric-kit evaluate chat_session.txt rubric.yaml results.csv \
#   --judge-panel-config panel.example.yaml

# Output CSV will include consensus metadata:
# - consensus_reached: Boolean indicating if threshold was met
# - consensus_count: Number of judges that agreed
# - judge_votes: Individual judge results (in judge_votes column if verbose)

